name: lint+test
on:
  push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - name: install
        run: npm install
      - name: lint:eslint
        run: npm run lint:eslint
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - name: install
        run: npm install
      - name: test
        run: npm run test
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
