name: lint
on:
  push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name setup-ssh
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH }}
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
